apiVersion: v1
kind: Secret
metadata:
  name: coder-db-url
  labels:
    {{- include "coder.labels" . | nindent 4 }}
data:
  POSTGRES_CONNECTION_URL: {{ template "postgresql_url" . }}
type: Opaque